vim.g["mapleader"] = ","
require("plugins")
vim.cmd("colorscheme gruvbox")
local option = require("options")
vim.g["python3_host_prog"] = "/usr/bin/python3"
local map = require("mappings")
vim.g["lightline"] = {active = {component = {charvaluehex = "0x%B", filename = "%f", modified = "%m"}, component_function = {gitbranch = "fugitive#head"}, left = {{"mode", "paste"}, {"cocstaus", "git", "readonly", "filename", "modified"}}, right = {{"lineinfo"}, {"charvaluehex"}, {"fileformat", "fileencoding", "filetype", "diagnostic"}}}, colorscheme = "gruvbox", separator = {left = "\238\130\176", right = "\238\130\178"}, subseparator = {left = "\238\130\177", right = "\238\130\179"}}
local ts = require("nvim-treesitter.configs")
ts.setup({ensure_installed = "maintained", highlight = {enable = true}})
local lsp = require("lspconfig")
local lspfuzzy = require("lspfuzzy")
lsp.ccls.setup({})
lspfuzzy.setup({})
map("n", "<space>,", "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>")
map("n", "<space>;", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>")
map("n", "<space>a", "<cmd>lua vim.lsp.buf.code_action()<CR>")
map("n", "<space>d", "<cmd>lua vim.lsp.buf.definition()<CR>")
map("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>")
map("n", "<space>h", "<cmd>lua vim.lsp.buf.hover()<CR>")
map("n", "<space>m", "<cmd>lua vim.lsp.buf.rename()<CR>")
map("n", "<space>r", "<cmd>lua vim.lsp.buf.references()<CR>")
map("n", "<space>s", "<cmd>lua vim.lsp.buf.document_symbol()<CR>")
vim.g["fzf_action"] = {["ctrl-t"] = "tab split", ["ctrl-v"] = "vsplit", ["ctrl-x"] = "split"}
vim.g["fzf_history_dir"] = "~/.local/share/fzf-history"
map("", "<leader>f", ":Files<cr>")
map("", "<leader>b", ":Buffers<cr>")
map("n", "<leader>g", ":Rg<cr>")
map("n", "<leader>t", ":Tags<cr>")
map("n", "<leader>m", ":Marks<cr>")
local tp = require("telescope")
local actions = require("telescope.actions")
local previewers = require("telescope.previewers")
tp.setup({defaults = {mappings = {i = {["<esc>"] = actions.close}}}})
map("n", "<leader>ff", "<cmd>Telescope find_files<cr>")
map("n", "<leader>fg", "<cmd>Telescope live_grep<cr>")
map("n", "<leader>fb", "<cmd>Telescope buffers<cr>")
map("n", "<leader>fh", "<cmd>Telescope help_tags<cr>")
return nil
