vim.g["mapleader"] = ","
require("plugins")
vim.cmd("colorscheme gruvbox")
local option = require("options")
vim.g["python3_host_prog"] = "/usr/bin/python3"
local map = require("mappings")
local ts = require("nvim-treesitter.configs")
ts.setup({ensure_installed = "maintained", highlight = {enable = true}})
local nvim_lsp = require("lspconfig")
local completion = require("completion")
local function _0_(client)
  assert((nil ~= client), string.format("Missing argument %s on %s:%s", "client", "fnl/main.fnl", 26))
  return completion.on_attach(client)
end
nvim_lsp.rust_analyzer.setup({on_attach = _0_})
nvim_lsp.ccls.setup({})
vim.g["lightline"] = {active = {component = {charvaluehex = "0x%B", filename = "%f", modified = "%m"}, component_function = {gitbranch = "fugitive#head"}, left = {{"mode", "paste"}, {"cocstaus", "git", "readonly", "filename", "modified"}}, right = {{"lineinfo"}, {"charvaluehex"}, {"fileformat", "fileencoding", "filetype", "diagnostic"}}}, colorscheme = "gruvbox", separator = {left = "\238\130\176", right = "\238\130\178"}, subseparator = {left = "\238\130\177", right = "\238\130\179"}}
map("n", "<space>,", "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>")
map("n", "<space>;", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>")
map("n", "<space>a", "<cmd>lua vim.lsp.buf.code_action()<CR>")
map("n", "<space>d", "<cmd>lua vim.lsp.buf.definition()<CR>")
map("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>")
map("n", "<space>h", "<cmd>lua vim.lsp.buf.hover()<CR>")
map("n", "<space>m", "<cmd>lua vim.lsp.buf.rename()<CR>")
map("n", "<space>r", "<cmd>lua vim.lsp.buf.references()<CR>")
map("n", "<space>s", "<cmd>lua vim.lsp.buf.document_symbol()<CR>")
map("", "<leader>f", ":Files<cr>")
map("", "<leader>b", ":Buffers<cr>")
map("n", "<leader>g", ":Rg<cr>")
map("n", "<leader>t", ":Tags<cr>")
map("n", "<leader>m", ":Marks<cr>")
local tp = require("telescope")
local actions = require("telescope.actions")
local previewers = require("telescope.previewers")
tp.setup({defaults = {mappings = {i = {["<esc>"] = actions.close}}}})
map("n", "<leader>ff", "<cmd>Telescope find_files<cr>")
map("n", "<leader>fg", "<cmd>Telescope live_grep<cr>")
map("n", "<leader>fb", "<cmd>Telescope buffers<cr>")
map("n", "<leader>fh", "<cmd>Telescope help_tags<cr>")
vim.cmd("cmap :w :w!")
return nil
