local install_path = (vim.fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim")
if (vim.fn.empty(vim.fn.glob(install_path)) ~= 0) then
  print("installing packer...")
  vim.api.nvim_command(("!git clone https://github.com/wbthomason/packer.nvim" .. " " .. install_path))
  vim.api.nvim_command("packadd packer.nvim")
end
local packer = require("packer")
local util = require("packer.util")
packer.init({package_root = util.join_paths(vim.fn.stdpath("data"), "site", "pack")})
local function _1_()
  use("wbthomason/packer.nvim")
  use({"kyazdani42/nvim-tree.lua", requires = "kyazdani42/nvim-web-devicons"})
  use("morhetz/gruvbox")
  use("tpope/vim-repeat")
  use("tpope/vim-surround")
  use("tpope/vim-fugitive")
  use("itchyny/lightline.vim")
  use("nvim-lua/lsp-status.nvim")
  use({"nvim-lua/telescope.nvim", disabled = true, requires = {"nvim-lua/plenary.nvim", "nvim-lua/popup.nvim"}})
  use({"junegunn/fzf", run = vim.fn["fzf#install"]})
  use("gfanto/fzf-lsp.nvim")
  use("b3nj5m1n/kommentary")
  use("airblade/vim-gitgutter")
  use("APZelos/blamer.nvim")
  use({"nvim-treesitter/nvim-treesitter", opt = true})
  use("neovim/nvim-lspconfig")
  use("nvim-lua/completion-nvim")
  use("anott03/nvim-lspinstall")
  use("unblevable/quick-scope")
  use("rust-lang/rust.vim")
  return nil
end
packer.startup(_1_)
return nil
