vim.cmd("packadd packer.nvim")
local packer = require("packer")
local util = require("packer.util")
packer.init({package_root = util.join_paths(vim.fn.stdpath("data"), "site", "pack")})
local function packer_startup()
  use("wbthomason/packer.nvim")
  use("morhetz/gruvbox")
  use("airblade/vim-gitgutter")
  use("APZelos/blamer.nvim")
  use({"nvim-treesitter/nvim-treesitter", opt = true})
  use("sheerun/vim-polyglot")
  use("neovim/nvim-lspconfig")
  use("nvim-lua/completion-nvim")
  use("anott03/nvim-lspinstall")
  use("nvim-lua/popup.nvim")
  use("nvim-lua/plenary.nvim")
  use("nvim-lua/telescope.nvim")
  use("jremmen/vim-ripgrep")
  use("itchyny/lightline.vim")
  use("itchyny/vim-gitbranch")
  use("kyazdani42/nvim-web-devicons")
  use("kyazdani42/nvim-tree.lua")
  use("tpope/vim-commentary")
  use("tpope/vim-repeat")
  use("tpope/vim-surround")
  use("unblevable/quick-scope")
  use("rust-lang/rust.vim")
  use("tpope/vim-dispatch")
  return nil
end
packer.startup(packer_startup)
return nil
