require "plug-config/kommentary"
require "plug-config/nvim-lsp"
require "plug-config/nvim-tree"
require "plug-config/treesitter"
require "plug-config/lightline"
require "plug-config/fzf"
require "plug-config/keys"
require "plug-config/telescope"
